# Generated by Django 4.0.5 on 2022-06-18 12:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='tournaments',
            field=models.ManyToManyField(related_name='players', to='tournament.tournament'),
        ),
        migrations.AlterField(
            model_name='player',
            name='ranking',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
