# Generated by Django 4.0.5 on 2022-06-21 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_player_tournaments_alter_player_ranking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='tournaments',
        ),
    ]
