# Generated by Django 4.0.5 on 2022-06-18 12:32

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('location', models.CharField(max_length=128, unique=True)),
                ('ranking', models.IntegerField(unique=True)),
                ('dates', django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), size=None)),
                ('description', models.CharField(max_length=128, unique=True)),
                ('game_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tournament.gametype')),
            ],
        ),
    ]
