# Generated by Django 4.0.5 on 2022-06-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_remove_tournament_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='location',
            field=models.CharField(max_length=128),
        ),
    ]
