# Generated by Django 4.0.5 on 2022-06-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_remove_player_tournaments'),
        ('tournament', '0003_alter_tournament_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='players',
            field=models.ManyToManyField(related_name='tournament', to='player.player'),
        ),
    ]
