# Generated by Django 4.0.5 on 2022-06-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_remove_player_tournaments'),
        ('tournament', '0004_tournament_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='players', to='player.player'),
        ),
    ]
