# Generated by Django 4.0.5 on 2022-06-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('round', '0005_alter_round_end_date_alter_round_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
