# Generated by Django 4.0.5 on 2022-06-21 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0002_player_tournaments_alter_player_ranking'),
        ('round', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1_score', models.FloatField()),
                ('player2_score', models.FloatField()),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='player.player')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='player.player')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round', to='round.round')),
            ],
        ),
    ]
